server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  #开启健康检查
    healthcheck:
      enabled: true
  instance:
    #租期到期时间
    lease-expiration-duration-in-seconds: 60
    #租期更新时间间隔，即每15秒发送一次心跳
    lease-renewal-interval-in-seconds: 15
spring:
  application:
    name: eureka-service

