spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oa
    password: xuhaixing
    url: jdbc:mysql://192.168.94.150:3306/oa?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    name: oa
  redis:
    host: 192.168.94.150
    port: 6379
    password: xuhaixing
    database: 1
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 2000d
    timeout: 5000d
  data:
    redis:
      repositories:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.94.150:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    #租期到期时间
    lease-expiration-duration-in-seconds: 60
    #租期更新时间间隔，即每15秒发送一次心跳
    lease-renewal-interval-in-seconds: 15
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}