spring:
  application:
    name: user-service

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml, classpath*:mybatis/custom-mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: info